package Teliko;
import java.sql.*;

//import Teliko.NewJFrameEggrafhNeouXrhsth;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antonis
 */
public class Arxikh extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameArxikh
     */
    public Arxikh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(899, 600));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Κωδικός Χρήστη");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 90, 150, 50);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setMaximumSize(new java.awt.Dimension(150, 50));
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 50));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 50));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(350, 30, 150, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Όνομα Χρήστη");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 30, 150, 50);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setToolTipText("");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(150, 50));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(150, 50));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(350, 90, 150, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Είσοδος");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 60, 150, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Εγγραφή");
        jButton2.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 430, 150, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Εγγραφή Νέων Χρηστών");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 430, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Teliko/LogoTheDoctor.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 910, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new EggrafhNeouXrhsth().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username=jTextField1.getText();
        String pswd=String.copyValueOf(jPasswordField1.getPassword());
        String password=null;
        String specialty=null;
        
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        }catch(Exception e){
            System.out.println("Unable to load Driver");
        }
        
        try{
            String connectionUrl = "jdbc:mysql://localhost:3306/iatrikosfakelos";
            String connectionUser = "antonis";
            String connectionPassword = "antonis";
            conn = DriverManager.getConnection(connectionUrl , connectionUser , connectionPassword);
        }catch(Exception e){
            System.out.println("Unable to connect to database");
        }
        
        if(conn!=null){
            try{
                stmt=conn.createStatement();
            }catch(SQLException e){
                System.out.println("Unable to create statement");
            }
         }
        
        if(stmt!=null){
            try{
                rs=stmt.executeQuery("select * from ergazomenoi where username='"+username+"'");
            }catch(SQLException e){
                System.out.println("Unable to select from the databese");
            }
        }
        
        if(rs!=null){
            try{
                while(rs.next()){
                    password=rs.getString("password");
                    specialty=rs.getString("specialty");
                }                
            }catch(SQLException e){
                System.out.println("Unable to read from rs.");
            }            
        }
        
        try {
            if (rs != null) { rs.close(); }
            if (conn != null) { conn.close(); }
            if (stmt != null) { stmt.close(); }
        } catch (SQLException e) {
            System.out.println("Unable to close connection");
        }
        
        if(pswd.equals(password) && specialty.equals("Νοσοκόμος")){
            this.setVisible(false);
            new Nosokomos().setVisible(true);                                    
        }else if(pswd.equals(password) && specialty.equals("Ιατρός")){
            this.setVisible(false);
            new Iatros().setVisible(true);
        }else if(pswd.equals(password) && specialty.equals("Γραμματεία")){
            this.setVisible(false);
            new Grammateia().setVisible(true);
        }else{
            this.setVisible(false);
            new LathosEisodos().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arxikh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arxikh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arxikh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arxikh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arxikh().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
